# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import pyllamacpp_pb2 as pyllamacpp__pb2


class LlamaModelStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateText = channel.unary_unary(
                '/pyllamacpp.LlamaModel/GenerateText',
                request_serializer=pyllamacpp__pb2.GenerateTextRequest.SerializeToString,
                response_deserializer=pyllamacpp__pb2.GenerateTextResponse.FromString,
                )
        self.UpdateParameters = channel.unary_unary(
                '/pyllamacpp.LlamaModel/UpdateParameters',
                request_serializer=pyllamacpp__pb2.UpdateParametersRequest.SerializeToString,
                response_deserializer=pyllamacpp__pb2.UpdateParametersResponse.FromString,
                )


class LlamaModelServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateParameters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LlamaModelServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateText': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateText,
                    request_deserializer=pyllamacpp__pb2.GenerateTextRequest.FromString,
                    response_serializer=pyllamacpp__pb2.GenerateTextResponse.SerializeToString,
            ),
            'UpdateParameters': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateParameters,
                    request_deserializer=pyllamacpp__pb2.UpdateParametersRequest.FromString,
                    response_serializer=pyllamacpp__pb2.UpdateParametersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pyllamacpp.LlamaModel', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LlamaModel(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pyllamacpp.LlamaModel/GenerateText',
            pyllamacpp__pb2.GenerateTextRequest.SerializeToString,
            pyllamacpp__pb2.GenerateTextResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateParameters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pyllamacpp.LlamaModel/UpdateParameters',
            pyllamacpp__pb2.UpdateParametersRequest.SerializeToString,
            pyllamacpp__pb2.UpdateParametersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
